version: 1.0.{build}
image: Visual Studio 2022
platform:
- x64
environment:
  APPVEYOR_RDP_PASSWORD: Carin123!
  VCVAR2022: 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsamd64_x86.bat'  
before_build:
- ps: |
    # ...example script to set the proper flags for vcvarsall ...
    # syntax: vcvarsall.bat [architecture] [platform_type] [winsdk_version] [-vcvars_ver=vcversion]
    $Architecture = $env:PLATFORM # simplified, works for x86 and x64
    if ("$env:APPVEYOR_BUILD_WORKER_IMAGE" -eq "Visual Studio 2022") {
      $env:VCVARSALL = "`"$env:VCVAR2022`" $Architecture"
    } else {
      $env:VCVARSALL = "`"$env:VCVAR2017`" $Architecture"
    }
- call %VCVARSALL%
build_script:
- cmd: >-
    cd RTPApp

    cmake . --preset x64-release

    cd out\build\x64-release

    cmake --build .
test_script:
- cmd: >- 
        NetworkTest\NetworkTest.exe --gtest_output=xml:testresults.xml
        
        CommonTest\CommonTest.exe --gtest_output=xml:testresults.xml
notifications:
- provider: Email
  to:
  - ideic75@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true